on:
  pull_request:
    branches:
      - master
permissions:
  contents: write
name: Generate V1-Only Permissions Data
jobs:
  generate_v1_permissions:
    name: Generate V1-Only Permissions Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Run Generate V1-Only Permissions Data
        uses: wscalf/rbac-config-actions/generate-v1-only-permissions@add-generate-v1-only-permissions-action
        with:
          ksl_src: configs/stage/schemas/src
          rbac_permissions: configs/stage/permissions


