on:
  push:
    branches:
      - master
name: Schema generation
jobs:
  generate_schema:
    name: Generate Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Clone ksl-schema-language repo
        run: git clone --depth=1 https://github.com/project-kessel/ksl-schema-language.git

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
      
      - name: Build KSL compiler binary
        run: |
          cd ksl-schema-language
          mkdir -p bin/
          go build -gcflags "all=-N -l" -o ./bin/ ./...
          cd ..
            
      - name: Run KSL compiler
        run: |
          ./ksl-schema-language/bin/ksl -o configs/stage/schemas/schema.zed configs/stage/schemas/src/*.ksl
          ./ksl-schema-language/bin/ksl -o configs/prod/schemas/schema.zed configs/prod/schemas/src/*.ksl
      
      - name: Remove KSL repo
        run: rm -rf ksl-schema-language/

      - name: Create a PR with Schema changes
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated schema generation'
          title: Update [GitHub] - Automated Schema Generation