on:
  pull_request:
    branches:
      - master
permissions:
  contents: read
  contents: write
name: Schema generation & validation
jobs:
  generate_schema:
    name: Generate & Validate Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}

      # generate schemas
      - name: Clone ksl-schema-language repo
        run: git clone --depth=1 https://github.com/project-kessel/ksl-schema-language.git

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
      
      - name: Build KSL compiler binary
        run: |
          cd ksl-schema-language
          mkdir -p bin/
          go build -gcflags "all=-N -l" -o ./bin/ ./...
          cd ..
            
      - name: Run KSL compiler
        run: |
          ./ksl-schema-language/bin/ksl -o configs/stage/schemas/schema.zed configs/stage/schemas/src/*.ksl configs/stage/schemas/src/*.json
          ./ksl-schema-language/bin/ksl -o configs/prod/schemas/schema.zed configs/prod/schemas/src/*.ksl configs/prod/schemas/src/*.json
      
      - name: Remove KSL repo
        run: rm -rf ksl-schema-language/

      # commit changed schema back to PR.
      - uses: stefanzweifel/git-auto-commit-action@v5

      # validate generated schemas
      - name: Validate Stage Schema
        uses: "authzed/action-spicedb-validate@v1"
        with:
          validationfile: "configs/stage/schemas/schema.zed"
      - name: Validate Prod Schema
        uses: "authzed/action-spicedb-validate@v1"
        with:
          validationfile: "configs/prod/schemas/schema.zed"